  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D4860C8E9EB741BAB6D34284B5717B9D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B1A405E946574B68877241FC01AE6691 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_861FCF0230C04B0696B8A22182F563F9 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'warden-app-back'
          slot-name: 'Production'
          package: './node-app'


          